# Generated by Django 2.2.3 on 2019-07-10 14:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_auto_20190705_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='clients_photos'),
        ),
        migrations.AlterField(
            model_name='person',
            name='date',
            field=models.DateField(default=datetime.date.today, verbose_name='Data de Nascimento'),
        ),
    ]
