# Generated by Django 2.2.3 on 2019-07-18 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_remove_person_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='bio',
            new_name='Descrição',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='photo',
            new_name='Foto',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='age',
            new_name='Idade',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='first_name',
            new_name='Nome',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='salary',
            new_name='Salário',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='last_name',
            new_name='Sobrenome',
        ),
    ]
