# Generated by Django 2.2.3 on 2019-07-22 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0005_auto_20190718_1532'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='Nome',
            new_name='first_name',
        ),
    ]
