# Generated by Django 2.2.3 on 2019-07-22 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0006_auto_20190722_1242'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='first_name',
            new_name='Nome',
        ),
    ]
